services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Krasnoyarsk
    volumes:
      - /home/gan/stacks/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
networks:
  dockge_default:
    external: true
