services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Krasnoyarsk
    volumes:
      - /home/gan/stacks/heimdall/config:/config
    ports:
      - 8443:443
    restart: unless-stopped
networks:
  npm_default:
    external: true
