services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Krasnoyrsk
    volumes:
      - /home/gan/stacks/lidarr/config:/config
      - /mnt/Media:/music #optional
      - /mnt/Media/lidarr:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
networks: {}
